// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmpzg61ag33_ogYyoHj3vHqoK79XERbZ8',
    appId: '1:846663692598:android:1d401fee242d657b0a4397',
    messagingSenderId: '846663692598',
    projectId: 'taksio-ebc54',
    storageBucket: 'taksio-ebc54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJUXSpCwfs6N99ZVNHFIbN2K-ZE-I8PBk',
    appId: '1:846663692598:ios:b9f87a64c2c903230a4397',
    messagingSenderId: '846663692598',
    projectId: 'taksio-ebc54',
    storageBucket: 'taksio-ebc54.firebasestorage.app',
    iosBundleId: 'com.example.taksio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJUXSpCwfs6N99ZVNHFIbN2K-ZE-I8PBk',
    appId: '1:846663692598:ios:b9f87a64c2c903230a4397',
    messagingSenderId: '846663692598',
    projectId: 'taksio-ebc54',
    storageBucket: 'taksio-ebc54.firebasestorage.app',
    iosBundleId: 'com.example.taksio',
  );
}
